#!/usr/bin/env bash
#Install nginx web server listening on port 80

sudo apt-get update -y
sudo apt-get install nginx -y

sudo mkdir -p /var/www/html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
