#!/usr/bin/env bash
#Bash script containing commands to automatically configure a Ubuntu machine
#perfoming a 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\trewrite ^\/redirec_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
