#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\trewrite ^\/redirec_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

#create 404error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed-i "s/listen 80 default_server;/replacement/" /etc/nginx/sites-enabled/default

#after implementing changes restart nginx

sudo service nginx restart
