#!/usr/bin/env bash
# Bash script that displays listening ports:
# That only shows listening sockets
# That shows the PID and name of the program to which each socket belongs

    if [ "$(id -u)" != "0" ]; then
    echo "Please run this script as root."
    exit 1
fi

lsof -i -n -P | awk '$1 == "LISTEN" {print "Port:", $9, "PID:", $2, "Program:", $1}'
