#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely

highland(){
	echo "I am invincible!!!"
}
trap highland SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
