#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

count=0
while [ $count -le 12 ]
do
	i=1
	echo "Hour: $count"
	while [ $i -le 59 ]
	do
		echo "$i"
		i=$((i+1))
	done
	count=$((count+1))
done
