#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8.
#	The checker is running on Docker, so make sure to read this

if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root."
  exit 1
fi

echo "127.0.0.2 localhost" >> /etc/hosts

echo "8.8.8.8 facebook.com" >> /etc/hosts

if command -v systemd-resolve &>/dev/null; then
  systemctl restart systemd-resolved
elif command -v service &>/dev/null; then
  service nscd restart
elif command -v service &>/dev/null; then
  service dns-clean restart
fi

echo "Server configuration complete. localhost now resolves to 127.0.0.2, and facebook.com resolves to 8.8.8.8."
